"""added items table and relation one user to many items

Revision ID: a12db3d2543a
Revises: 1583697c10a7
Create Date: 2026-02-24 03:42:55.154074

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a12db3d2543a"
down_revision: Union[str, Sequence[str], None] = "1583697c10a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.Enum("LOST", "FOUND", name="itemtype"), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "ELECTRONICS",
                "PETS",
                "KEYS",
                "WALLET",
                "BAG",
                "DOCUMENTS",
                "CLOTHING",
                "JEWELRY",
                "OTHER",
                name="itemcategory",
            ),
            nullable=False,
        ),
        sa.Column("date_occurred", sa.Date(), nullable=True),
        sa.Column("lat", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("lng", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("location_name", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum("OPEN", "CLAIMED", "RESOLVED", "REMOVED", name="itemstatus"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("items")
    # ### end Alembic commands ###
